### ISSUE TITLE
Is it legal for llama2 to fine tune with other language?

### ISSUE THREAD

**Issue by SetoKaiba** [facebookresearch/llama#395] opened 2023-07-19 08:12 UTC
It's not prohibited by the Acceptable Use Policy and Licensing Agreement for Llama 2.
But it's mentioned in the hugging face model card.
https://huggingface.co/meta-llama/Llama-2-13b-chat-hf#intended-use

Is it not intended but allowed? Thank you.

**Comment by AhmedIssa11** [comment] 2023-07-19 14:44
I found this part, I don't know why using the model in other language is out of scope.
"Out-of-scope Uses Use in any manner that violates applicable laws or regulations (including trade compliance laws).Use in languages other than English. Use in any other way that is prohibited by the Acceptable Use Policy and Licensing Agreement for Llama 2"

**Comment by Jhangsy** [comment] 2023-07-21 09:19
Same question.

**Comment by echogit** [comment] 2023-08-09 09:19
Found this looking for that weird "Intended Use"section, Glad to know that it is only in HF that it shows.

**Comment by andrewchungg** [comment] 2023-09-07 04:53
Llama 2 is intended for commercial and research use in English only. Other languages are out-of-scope. Use of other languages in any other way is prohibited by the Acceptable Use Policy and Licensing Agreement for Llama 2.

**Comment by jspisak** [comment] 2023-09-15 21:26
Sorry folks - there is some nuance here and I'll do my best to help clear it up. No, it is NOT a violation of the acceptable use policy (AUP) to finetune on a non-english language and then use commercially as long as you follow the AUP and the terms of the license. In fact that's a feature not a bug and we hope people do that.. :)  

We did however include some things in the responsible use guide around this because documentation and support doesn't yet exist for languages beyond english. Llama 2 itself is really english language centric and you can read the paper for more details here.  

I hope this helps!!

**Closed** 2023-09-15 21:27 UTC
Labels: documentation, legal

**Comment by rami2102** [comment] 2023-11-05 21:48
How does the software community that wants to use Llama 2 for commercial use know if it is allowed or not? Part of the Llama 2 ToS includes
"Additional Commercial Terms If, on the Llama 2 version release date, the monthly active users of the products or services made available by or for the licensee, or the licensee's affiliates, are greater than 700 million monthly active users in the preceding calendar month, you must request a license from Meta, which Meta may grant to you in its sole discretion, and you are not authorized to exercise any of the rights under this Agreement unless or until Meta otherwise expressly grants you such rights."

What does the 700 million refer to?  Is it the number of global users of all companies that use some Llama 2 features? If so, how do we know if it is lower or greater than 700 million on the release date? Especially when Meta has much more users and maybe already uses Llama 2 for all its users, maybe its forbidden for everyone?
