### ISSUE TITLE
"Unable to establish SSL connection" error when running ./download.sh

### ISSUE THREAD

**Issue by scilligence** [facebookresearch/llama#411] opened 2023-07-19 14:33 UTC
Hi, I got "Unable to establish SSL connection" error when running ./download.sh in my Windows system:

![image](https://github.com/facebookresearch/llama/assets/19560173/6e545792-70a4-44f5-8f16-b4b00e660ee2)

Can somebody help?

**Comment by auxon** [comment] 2023-07-19 17:19
I had this problem too, because I was using an older version of wget.  I then used the Windows x64 exe available from https://eternallybored.org/misc/wget/ and it works.

**Comment by scilligence** [comment] 2023-07-19 17:56
@auxon You save me.  Thanks a lot for the trick

**Comment by tweetyleaf2** [comment] 2023-07-19 18:52
@auxon This solved this issue for me too. Thank you. (Windows 11, git bash).

**Comment by AndreasGiersch** [comment] 2023-08-04 11:43
@auxon Thank you very much! Can confirm this works on windows 10.

Reproducing what I did, in case any other windows users are still struggling: 

- delete local llama repo
- clone llama repo again
- request download link from meta
- copy download link from email (make sure to copy it correctly. It should start with 'https://download.llamameta.net/')
- while waiting, download the newest version of wget.exe for windows (from the URL as previously commented by @auxon) by clicking the "EXE" hyperlink as highlighted in the screenshot
![image](https://github.com/facebookresearch/llama/assets/54770323/464bac66-54c5-4d37-ae6a-b77ba0fac848)
- go 'C:\Program Files' and create a new folder 'GnuWin64'
- copy the wget.exe file into this newly created folder
- edit the PATH variable and add the path to wget.exe
- open download.sh in llama repo
- (within download.sh) delete the lines prompting the user for the download link
- (within download.sh) add a new line PRESIGNED_URL="<paste download link here>" (could look as follows)
![image](https://github.com/facebookresearch/llama/assets/54770323/2cedcb25-af0c-458b-9268-a6bcc9af7b1c)
- save download.sh file
- execute download.sh in cmd

**Comment by lmarcon** [comment] 2023-09-01 10:54
This issue seems solved as per comments above, closing. Thanks!

**Closed by lmarcon** 2023-09-01 10:54 UTC
