### ISSUE TITLE
I've been thinking about how to obtain the hidden state of the last layer of Llama2 after calling the chat_completion method, but I'm not sure how to implement it. I hope to get some answers.

### ISSUE THREAD

**Issue by Eyryu** [facebookresearch/llama#920] opened 2023-11-15 11:19 UTC
I've been thinking about how to obtain the hidden state of the last layer of Llama2 after calling the chat_completion method, but I'm not sure how to implement it. I hope to get some answers.

_オリジナルは @jjkk123456 が https://github.com/facebookresearch/llama/issues/909 にポスト_

**Comment by fbnav** [comment] 2023-11-15 18:30
Duplicate of https://github.com/facebookresearch/llama/issues/921. Closing.

**Closed by fbnav** 2023-11-15 18:30 UTC
Labels: duplicate

**Comment by tanshuai0219** [comment] 2024-04-13 03:37
any answer? I meet the same question.
