### ISSUE TITLE
How to deploy web services for llama13B(or bigger model)

### ISSUE THREAD

**Issue by xiangh8** [facebookresearch/llama#85] opened 2023-03-03 07:59 UTC
I have two A100-40G and tried to deploy web services through flask. I succeeded when use 7B but failed in MP>1 model. Maybe someone can tell me how to modify my code?

```
import argparse
from flask import Flask, request, jsonify
from waitress import serve
from typing import Tuple
import os
import sys
import torch
import time
import json
from pathlib import Path
import torch.distributed as dist
from fairscale.nn.model_parallel.initialize import initialize_model_parallel

from llama import ModelArgs, Transformer, Tokenizer, LLaMA

app = Flask(__name__)
def setup_model_parallel() -> Tuple[int, int]:
    local_rank = int(os.environ.get("LOCAL_RANK", -1))
    world_size = int(os.environ.get("WORLD_SIZE", -1))
    print(f"local:{local_rank},world:{world_size}")
    dist.init_process_group("nccl")
    initialize_model_parallel(world_size)
    torch.cuda.set_device(local_rank)

    # seed must be the same in all processes
    torch.manual_seed(1)
    return local_rank, world_size


def load(ckpt_dir: str, tokenizer_path: str, local_rank: int, world_size: int) -> LLaMA:
    start_time = time.time()
    checkpoints = sorted(Path(ckpt_dir).glob("*.pth"))
    assert (
        world_size == len(checkpoints)
    ), f"Loading a checkpoint for MP={len(checkpoints)} but world size is {world_size}"
    ckpt_path = checkpoints[local_rank]
    print("Loading")

    checkpoint = torch.load(ckpt_path, map_location="cpu")
    with open(Path(ckpt_dir) / "params.json", "r") as f:
        params = json.loads(f.read())

    model_args: ModelArgs = ModelArgs(max_seq_len=1024, max_batch_size=8, **params)
    tokenizer = Tokenizer(model_path=tokenizer_path)
    model_args.vocab_size = tokenizer.n_words
    torch.set_default_tensor_type(torch.cuda.HalfTensor)
    model = Transformer(model_args)
    torch.set_default_tensor_type(torch.FloatTensor)
    model.load_state_dict(checkpoint, strict=False)
    generator = LLaMA(model, tokenizer)
    print(f"Loaded in {time.time() - start_time:.2f} seconds")
    return generator



if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--ckpt_dir")
    parser.add_argument("--tokenizer_path", type=str)
    parser.add_argument("--port", type=int,default=7860)
    args = parser.parse_args()
    local_rank, world_size = setup_model_parallel()
    # if local_rank > 0:
    #     sys.stdout = open(os.devnull, 'w')
    print(f"load at {local_rank}")
    generator = load(args.ckpt_dir, args.tokenizer_path, local_rank, world_size)
    print(f"load gen{local_rank}")
    prompts = ["The capital of Germany is the city of", "Here is my sonnet in the style of Shakespeare about an artificial intelligence:"]
    results = generator.generate(prompts, max_gen_len=20, temperature=0.8, top_p=0.95)
    print(results)
    #--------------------------------------------------------WHAT I ADDED--------------------------------------------------------------
    @app.route("/generate_text", methods=["POST"])
    def generate():
        input = request.json
        context = input["context"]
        input_text = [input["text"]]
        max_gen_len= input["max_gen_len"]        results = generator.generate(input_text, max_gen_len=max_gen_len, temperature=0.8, top_p=0.95)
        return results
    serve(app, host="0.0.0.0", port=args.port+local_rank)
```

This deploys two interfaces. When I call one of them, the following error occurs, and the other one didn't respond.

` RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0! (when checking argument for argument index in method wrapper__index_select)`

**Comment by Anomyous1** [comment] 2023-03-03 08:48
![image](https://user-images.githubusercontent.com/125929699/222674624-9307822b-198c-4a46-9db0-4db5261e9bba.png)

**Comment by Anomyous1** [comment] 2023-03-03 08:50
![image](https://user-images.githubusercontent.com/125929699/222675058-dc844b70-763e-40af-94de-8ec0eabc9d1e.png)

**Comment by loganlebanoff** [comment] 2023-03-06 14:55
See here: https://github.com/facebookresearch/llama/issues/84#issuecomment-1456285764

**Comment by albertodepaola** [comment] 2023-09-06 17:28
duplicate of #84

**Closed by albertodepaola** 2023-09-06 17:28 UTC
Labels: duplicate
