### ISSUE TITLE
Running example got error: torch.distributed.elastic.multiprocessing.api:failed

### ISSUE THREAD

**Issue by szihai** [facebookresearch/llama#461] opened 2023-07-20 17:20 UTC
I'm testing with the example in README
`torchrun --nproc_per_node 1 example_text_completion.py \
    --ckpt_dir llama-2-7b/ \
    --tokenizer_path tokenizer.model \
    --max_seq_len 128 --max_batch_size 4`
And got this error:
` >initializing model parallel with size 1
  >initializing ddp with size 1
  >initializing pipeline with size 1
**ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -9) local_rank: 0 (pid: 2667) of binary: /usr/bin/python3**
Traceback (most recent call last):
  File "/home/xxx/.local/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/xxx/.local/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/xxx/.local/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/xxx/.local/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/xxx/.local/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/xxx/.local/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
===========================================================
example_text_completion.py FAILED
-----------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
-----------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-07-20_16:14:26
  host      : testvm.us-east4-c.c.xxx.internal
  rank      : 0 (local_rank: 0)
  exitcode  : -9 (pid: 2667)
  error_file: <N/A>
  traceback : Signal 9 (SIGKILL) received by PID 2667
===========================================================`

I'm running this on a GCP VM with 1 GPU.
![image](https://github.com/facebookresearch/llama/assets/26101651/66f17edc-bd01-4c23-bed7-f52a1395e246)

The VM configuration:
![image](https://github.com/facebookresearch/llama/assets/26101651/6e7055c4-eb9e-4f4e-9191-49809dd2bf57)
And memory info:
![image](https://github.com/facebookresearch/llama/assets/26101651/500e2948-239d-471c-9b26-6c9fe673446b)

Please advise on how to proceed.

**Comment by Jelly007** [comment] 2023-07-20 19:51
same here ...

**Comment by zaidorx** [comment] 2023-07-20 22:29
same here ...

**Comment by ram510** [comment] 2023-07-21 04:51
same issue on WSL Ubuntu

**Comment by guangchen811** [comment] 2023-07-21 06:52
Same issue.

**Comment by myndtrust** [comment] 2023-07-22 03:45
+1

**Comment by championii** [comment] 2023-07-22 07:09
+1

**Comment by skathpalia** [comment] 2023-07-22 17:09
+1

**Comment by skathpalia** [comment] 2023-07-22 17:11
+1 

torchrun --nproc_per_node 1 example_text_completion.py \ --ckpt_dir llama-2-7b/ \ --tokenizer_path tokenizer.model \ --max_seq_len 128 --max_batch_size 4
NOTE: Redirects are currently not supported in Windows or MacOs.
> initializing model parallel with size 1
> initializing ddp with size 1
> initializing pipeline with size 1
Traceback (most recent call last):
  File "/Volumes/Users/gitRepositories/llama/example_text_completion.py", line 56, in <module>
    fire.Fire(main)
  File "/Users/shivkathpalia/venv/lib/python3.11/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shivkathpalia/venv/lib/python3.11/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/Users/shivkathpalia/venv/lib/python3.11/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Users/gitRepositories/llama/example_text_completion.py", line 18, in main
    generator = Llama.build(
                ^^^^^^^^^^^^
  File "/Volumes/Users/gitRepositories/llama/llama/generation.py", line 92, in build
    assert len(checkpoints) > 0, f"no checkpoint files found in {ckpt_dir}"
           ^^^^^^^^^^^^^^^^^^^^
AssertionError: no checkpoint files found in  --ckpt_dir
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 63097) of binary: /Users/shivkathpalia/venv/bin/python
Traceback (most recent call last):
  File "/Users/shivkathpalia/venv/bin/torchrun", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/shivkathpalia/venv/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/shivkathpalia/venv/lib/python3.11/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/Users/shivkathpalia/venv/lib/python3.11/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/Users/shivkathpalia/venv/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shivkathpalia/venv/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
example_text_completion.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-07-22_10:06:34
  host      : 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 63097)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by ADD-eNavarro** [comment] 2023-07-25 08:42
+1

**Comment by pzim-devdata** [comment] 2023-07-25 14:54
I have solved it with a cpu installation by installing this : `https://github.com/krychu/llama` instead of `https://github.com/facebookresearch/llama`
Complete process to install : 
1. download the original version of Llama from : `https://github.com/facebookresearch/llama` and extract it to a `llama-main` folder
2. download th cpu version from : `https://github.com/krychu/llama` and extract it and replace files in the `llama-main` folder
3. run the `download.sh` script in a terminal, passing the URL provided when prompted to start the download
4. go to the `llama-main` folder
5. cretate an Python3 env : `python3 -m venv env` and activate it : `source env/bin/activate`
6. install the cpu version of pytorch : `python3 -m pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu #pour la version cpu`
7. install dependencies off llama : `python3 -m pip install -e .`
8. run if you have downloaded llama-2-7b : 
```
torchrun --nproc_per_node 1 example_text_completion.py \
    --ckpt_dir llama-2-7b/ \
    --tokenizer_path tokenizer.model \
    --max_seq_len 128 --max_batch_size 1 #(instead of 4)
```

**Comment by supreeth-c** [comment] 2023-07-30 11:00
torchrun --nproc_per_node 1 example_chat_completion.py --ckpt_dir llama-2-7b-chat --tokenizer_path tokenizer.model --max_seq_len 512 --max_batch_size 1
> initializing model parallel with size 1
> initializing ddp with size 1
> initializing pipeline with size 1
Loaded in 12.05 seconds
Traceback (most recent call last):
  File "/home/ubuntu/llama/example_chat_completion.py", line 73, in <module>
    fire.Fire(main)
  File "/home/ubuntu/miniconda3/lib/python3.11/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniconda3/lib/python3.11/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniconda3/lib/python3.11/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/llama/example_chat_completion.py", line 56, in main
    results = generator.chat_completion(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/llama/llama/generation.py", line 271, in chat_completion
    generation_tokens, generation_logprobs = self.generate(
                                             ^^^^^^^^^^^^^^
  File "/home/ubuntu/miniconda3/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/llama/llama/generation.py", line 118, in generate
    assert bsz <= params.max_batch_size, (bsz, params.max_batch_size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: (4, 1)
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 38534) of binary: /home/ubuntu/miniconda3/bin/python
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.0.1', 'console_scripts', 'torchrun')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniconda3/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniconda3/lib/python3.11/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/ubuntu/miniconda3/lib/python3.11/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/ubuntu/miniconda3/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniconda3/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
example_chat_completion.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-07-30_10:48:01
  host      : ip-172-11-31-118.ap-south-2.compute.internal
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 38534)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

**Comment by anamariaalvess** [comment] 2023-08-02 20:39
I have the same issue

**Comment by amponce** [comment] 2023-08-03 03:56
Same issue for me as well. I tried adding `export CUDA_VISIBLE_DEVICES=0` and it didn't seem to work. I noticed my cuda version isn't resolving correctly, does anyone know how to fix that?

![image](https://github.com/facebookresearch/llama/assets/3916436/4d86454e-872a-4c05-a1af-d7e5d57718ce)

**Comment by GenerativeAI4Finance** [comment] 2023-08-04 02:27
Error can occur, if you don't have a cuda device available. To check, run this command
>>> import torch
>>> print(torch.cuda.is_available())
False

If you see the result as false, then check that cuda is correctly configured and you have the cuda-enabled graphics driver.

If you don't have cuda-enabled device, then either you can use the cloud based pytorch containers eg. on Aws. Or run the code for device cpu. The second option needs code changes.

**Comment by szihai** [comment] 2023-08-04 05:59
My Cuda is installed. That script came back as True.

**Comment by itozer** [comment] 2023-08-07 04:37
I got the example to work by removing the last 2 parameters in the example. IE, remove:

    --tokenizer_path tokenizer.model \
    --max_seq_len 512 --max_batch_size 4

**Comment by hengzi52125** [comment] 2023-08-08 09:08
> I got the example to work by removing the last 2 parameters in the example. IE, remove:
> 
> --max_seq_len 512 --max_batch_size 4

It's work fro me, thanks!

**Comment by clems4ever** [comment] 2023-08-08 21:46
me too! Thanks @itozer!

**Comment by clems4ever** [comment] 2023-08-08 21:47
> > I got the example to work by removing the last 2 parameters in the example. IE, remove:
> > --max_seq_len 512 --max_batch_size 4
> 
> It's work fro me, thanks!

It worked for me too. Thanks @itozer!

**Comment by szihai** [comment] 2023-08-09 01:23
Taking both args out, I still got the same error :(

**Comment by szihai** [comment] 2023-08-09 23:07
I got it to work. 
I changed the vm type with an image that has CUDA 11 preinstalled. I used to go to nvidia website to install CUDA manually but it seemed to be the cause of issues.
I also increased to 2 GPUs. Not sure if it has any effect.
Then I ran the example as is, without any modification. 
And it worked!

**Comment by agunapal** [comment] 2023-09-06 19:42
Thanks for confirming it works. I have tested this on a single A10G with CUDA 11.8, it works.

**Closed by agunapal** 2023-09-06 19:42 UTC
Labels: model-usage
