### ISSUE TITLE
Anyone got approved?

### ISSUE THREAD

**Issue by jahaniam** [facebookresearch/llama#38] opened 2023-03-01 17:38 UTC
I requested a couple of days ago but haven't heard back. I was wondering if anyone was approved.

**Comment by HarrywillDr** [comment] 2023-03-01 18:20
me too

**Comment by neuhaus** [comment] 2023-03-01 20:38
duplicate of #26

**Comment by Syzygianinfern0** [comment] 2023-03-02 02:21
i just got approved

**Comment by vaibhavk97** [comment] 2023-03-02 02:42
Created a tiny PR for fixing the download script issue if anyone is facing that.

**Comment by rajuptvs** [comment] 2023-03-02 02:43
@vaibhavk97 any specific issue with download script, i just started the download, as of now it is downloading properly

**Comment by liujiaheng** [comment] 2023-03-02 02:46
![image](https://user-images.githubusercontent.com/27964642/222317821-1e7cff25-de3e-4105-8a41-e54776113a4e.png)
I have got the URL. But this URL is not worked

**Comment by arian81** [comment] 2023-03-02 02:47
I've gotten access but the download script is not working. I tried the new script from the @vaibhavk97 pr but it still doesn't work.

**Comment by vaibhavk97** [comment] 2023-03-02 02:48
What seems to be the issue? its working fine for me.

**Comment by Kashu7100** [comment] 2023-03-02 02:49
@liujiaheng @arian81 You need to modify the "PRESIGNED_URL" and "TARGET_FOLDER" fields in `download.sh`

**Comment by Deep1994** [comment] 2023-03-02 02:50
> ![image](https://user-images.githubusercontent.com/27964642/222317821-1e7cff25-de3e-4105-8a41-e54776113a4e.png) I have got the URL. But this URL is not worked

same error!

**Comment by arian81** [comment] 2023-03-02 02:51
@dst111dst @Deep1994  you're suppose to use the script. The link sent to your email is just a base email, other parameters need to be added to it using the download script.

**Comment by arian81** [comment] 2023-03-02 02:52
> What seems to be the issue? its working fine for me.

Oh i figured it out it was an issue on my end while fixing my script. I hope they merge the fix soon.

**Comment by abdoelsayed2016** [comment] 2023-03-02 02:59
set the url in the download.sh and also choose the target folder in linux use bash download.sh and in windows use git bash

**Comment by conceptofmind** [comment] 2023-03-02 03:02
Weights are downloading.

Set the pre-signed URL in the bash script
```python
PRESIGNED_URL="""    # where all files should end up

declare -A N_SHARD_DICT

N_SHARD_DICT["7B"]="0"
N_SHARD_DICT["13B"]="1"
N_SHARD_DICT["30B"]="3"
N_SHARD_DICT["65B"]="7"

echo "Downloading tokenizer"
wget ${PRESIGNED_URL/'*'/"tokenizer.model"} -O ${TARGET_FOLDER}"/tokenizer.model"
wget ${PRESIGNED_URL/'*'/"tokenizer_checklist.chk"} -O ${TARGET_FOLDER}"/tokenizer_checklist.chk"

(cd ${TARGET_FOLDER} && md5sum -c tokenizer_checklist.chk)

for i in ${MODEL_SIZE//,/ }
do
    echo "Downloading ${i}"
    mkdir -p ${TARGET_FOLDER}"/${i}"
    for s in $(seq -f "0%g" 0 ${N_SHARD_DICT[$i]})
    do
        wget ${PRESIGNED_URL/'*'/"${i}/consolidated.${s}.pth"} -O ${TARGET_FOLDER}"/${i}/consolidated.${s}.pth"
    done
    wget ${PRESIGNED_URL/'*'/"${i}/params.json"} -O ${TARGET_FOLDER}"/${i}/params.json"
    wget ${PRESIGNED_URL/'*'/"${i}/checklist.chk"} -O ${TARGET_FOLDER}"/${i}/checklist.chk"
    echo "Checking checksums"
    (cd ${TARGET_FOLDER}"/${i}" && md5sum -c checklist.chk)
done
```
Run
```bash
sudo bash download.sh
```

**Comment by ZurichRain** [comment] 2023-03-02 03:12
Thanks a lot! I just got approved~

**Comment by Amadeus-AI** [comment] 2023-03-02 03:23
just got approved

**Comment by mmsoby** [comment] 2023-03-02 03:44
Just got approved, download script worked as well, however I am stuck on running the example.py, getting an error

**Comment by wule1994** [comment] 2023-03-02 03:57
Just got approved！

**Comment by pauldog** [comment] 2023-03-02 05:27
Haven't heard anything. Guess I didn't get approved then ☹

**Comment by MiuGod0126** [comment] 2023-03-02 06:21
> I have got the URL. But this URL is not worked

use download.sh

**Comment by cedrickchee** [comment] 2023-03-02 07:06
Just got approved. But running `download.sh` returned network errors.

**Comment by andrewssobral** [comment] 2023-03-02 10:41
Just got approved, downloaded weights successfully.
<img width="349" alt="Screenshot 2023-03-02 at 11 40 39" src="https://user-images.githubusercontent.com/483114/222405730-5b9f455a-4d69-4b5b-be4a-e24dd4e68be9.png">

**Comment by HarrywillDr** [comment] 2023-03-02 11:37
> 

update approved now

**Comment by pauldog** [comment] 2023-03-02 15:59
Anyone approved without an .edu email address? This email is only for American universities?

**Comment by Winaung74** [comment] 2023-03-03 16:05
I tried to updated the provided url by access team and filled up target folder and run  download.sh in terminal with conda by Mac Os. Many errors came up. Does anyone help me what commands should I use to download the weights successfully? Thanks.

**Comment by ChongWu-Biostat** [comment] 2023-04-04 16:28
I applied a few weeks ago but did not get a response...

**Comment by neuhaus** [comment] 2023-04-11 12:26
@jahaniam  i suggest you close this issue.

**Comment by jahaniam** [comment] 2023-04-24 22:09
@neuhaus I am still waiting for the approval!

**Comment by lmarcon** [comment] 2023-09-05 09:53
@jahaniam do you still have problems with the approval?

**Comment by jspisak** [comment] 2023-09-06 18:11
Closing this issue but @jahaniam - please reopen if you are still having issues. thanks!

**Closed by jspisak** 2023-09-06 18:11 UTC
Labels: download-install, model-access
