### ISSUE TITLE
Connecting to download.llamameta.net (download.llamameta.net)|65.8.20.65|:443... connected.HTTP request sent, awaiting response... 403 Forbidden

### ISSUE THREAD

**Issue by Bateoriginal** [facebookresearch/llama#652] opened 2023-08-09 16:23 UTC
when I had md5sum, i got a message that 
Checking checksums
md5sum: checklist.chk: no properly formatted checksum lines found

now I installed md5sha1sum (i had to unlink coreutils). Now it keep running and never gives me an output after the message: "Checking checksums"

**Comment by andrewchungg** [comment] 2023-09-07 05:21
Duplicate of #653

**Closed by andrewchungg** 2023-09-07 05:21 UTC
Labels: download-install
