### ISSUE TITLE
RuntimeError: Distributed package doesn't have NCCL built in

### ISSUE THREAD

**Issue by qsimeon** [facebookresearch/llama#112] opened 2023-03-04 19:35 UTC
I was able to download the 7B weights on Mac OS Monterey. I get the following errors when I try to call the example from the README in my Terminal: ```torchrun --nproc_per_node 1 example.py --ckpt_dir download/model_size --tokenizer_path download/tokenizer.model```
```
RuntimeError: Distributed package doesn't have NCCL built in
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 51512) of binary: /Users/username/opt/anaconda3/envs/pytorch/bin/python
.
.
.
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
example.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-03-04_14:30:38
  host      : COMPUTER.tld
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 51512)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

**Comment by Inserian** [comment] 2023-03-04 19:42
You will have to manually add nccl. Make sure you have full privileges before choosing your install from nvidia. HPC-SDK is easiest, but downloading the tar and extracting to usr\local works the same.
https://docs.nvidia.com/deeplearning/nccl/install-guide/index.html

**Comment by tekspirit** [comment] 2023-03-05 00:20
I am on a mac pro with M1 max using 20 gpus - any idea how to resolve the nccl issue given no nVidia cards are installed?

**Comment by tekspirit** [comment] 2023-03-05 03:46
> I am on a mac pro with M1 max using 20 gpus - any idea how to resolve the nccl issue given no nVidia cards are installed?

I run `print(torch.backends.mps.is_built())` and it returns TRUE but when I set `torch.distributed.init_process_group("mps")` in example,py and run it, it complains mps cannot be found.
error `ValueError: Invalid backend: 'mps'`
Any ideas for getting the backend to run on m1?

**Comment by Inserian** [comment] 2023-03-05 19:43
You can't resolve nccl issues without nvidia. There are other process's that could be used as opposed to nccl, there are other libraries which allow parallel work around but I haven't bothered with them yet.
As far as torch run, it looks like you didn't input your MP value? If that still doesn't work, try python -m torch.distributed.run --nproc_per_node MP example.py --ckpt_dir $TARGET_FOLDER/model_size --tokenizer_path $TARGET_FOLDER/tokenizer.model (editing the mp value of course).

**Comment by andrewssobral** [comment] 2023-03-06 21:18
Hello guys,
I am also interested to see how to run LLaMA (e.g. 7B model) on Mac M1 or M2, any solution?

**Comment by Eurus-Holmes** [comment] 2023-03-07 21:36
same issue

**Comment by tekspirit** [comment] 2023-03-13 22:17
me too!

**Comment by bcouetil** [comment] 2023-03-28 19:45
I'm on a Macbook Pro M1 2022 and have the same problem.

**Comment by signalprime** [comment] 2023-04-19 01:31
> For MacOS, we have to use the C++ implementation : https://github.com/ggerganov/llama.cpp
> 
> Works like a charm on my side, with the 3 models that fit in my RAM ✌️

is it utilizing MPS acceleration from the M1 / M2 chip?

**Comment by AngelTs** [comment] 2023-05-11 15:02
I also have the NCCL error:
raise RuntimeError("Distributed package doesn't have NCCL " "built in")
untimeError: Distributed package doesn't have NCCL built in

**Comment by Sunjung-Dev** [comment] 2023-05-25 05:56
I have same problem ... I use M1 pro

**Comment by araby123** [comment] 2023-07-19 11:54
same issue I have on MacBook Pro m1 16gb

` raise RuntimeError("Distributed package doesn't have NCCL " "built in")
RuntimeError: Distributed package doesn't have NCCL built in
[2023-07-19 14:53:49,578] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 39243) of binary: /Users/mohammedaraby/miniconda3/envs/llama/bin/python
Traceback (most recent call last):
  File "/Users/mohammedaraby/miniconda3/envs/llama/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.1.0.dev20230718', 'console_scripts', 'torchrun')())
  File "/Users/mohammedaraby/miniconda3/envs/llama/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/Users/mohammedaraby/miniconda3/envs/llama/lib/python3.9/site-packages/torch/distributed/run.py", line 797, in main
    run(args)
  File "/Users/mohammedaraby/miniconda3/envs/llama/lib/python3.9/site-packages/torch/distributed/run.py", line 788, in run
    elastic_launch(
  File "/Users/mohammedaraby/miniconda3/envs/llama/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/Users/mohammedaraby/miniconda3/envs/llama/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
example_chat_completion.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-07-19_14:53:49
  host      : 171.0.168.192.in-addr.arpa
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 39243)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
`

**Comment by bcouetil** [comment] 2023-07-19 19:25
> > For MacOS, we have to use the C++ implementation : https://github.com/ggerganov/llama.cpp
> > Works like a charm on my side, with the 3 models that fit in my RAM ✌️
> 
> is it utilizing MPS acceleration from the M1 / M2 chip?

It utilizes my iGPU to it's fullest, and not much CPU, if this is your question.

**Comment by sixian-C** [comment] 2023-07-21 02:59
I have the same error when running `torchrun --nproc_per_node 1 example.py --ckpt_dir download/model_size --tokenizer_path download/tokenizer.model` in my windows 11 conda environment, any solution?

**Comment by aggiee** [comment] 2023-07-21 21:52
I was able to run Llama 2 7B on Mac M2 with (https://github.com/aggiee/llama-v2-mps)

**Comment by 3zerevelt** [comment] 2023-07-21 22:31
> I was able to run Llama 2 7B on Mac M2 with (https://github.com/aggiee/llama-v2-mps)

your code returns an error message indicating that the function torch.polar() is not implemented for the Metal Performance Shaders (MPS) ??  I'm also running on an M2 Mac.

**Comment by g8gg** [comment] 2023-07-22 00:35
I have same problem ... I use M1 pro

**Comment by aggiee** [comment] 2023-07-22 19:02
If you are referring to the following message, it is expected. It's due to M1/M2/MPS not supporting polar.out operator. It falls back to CPU for that specific operation and the warning is to inform the user about it:
"_UserWarning: The operator 'aten::polar.out' is not currently supported on the MPS backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at /private/var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_1aidzjezue/croot/pytorch_1687856425340/work/aten/src/ATen/mps/MPSFallback.mm:11.)
  freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64_"

The code should run past that.

**Comment by araby123** [comment] 2023-07-23 12:13
> If you are referring to the following message, it is expected. It's due to M1/M2/MPS not supporting polar.out operator. It falls back to CPU for that specific operation and the warning is to inform the user about it: "_UserWarning: The operator 'aten::polar.out' is not currently supported on the MPS backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at /private/var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_1aidzjezue/croot/pytorch_1687856425340/work/aten/src/ATen/mps/MPSFallback.mm:11.) freqs_cis = torch.polar(torch.ones_like(freqs), freqs) # complex64_"
> 
> The solution is to **set PYTORCH_ENABLE_MPS_FALLBACK=1 env variable** to run this code. That should make it work (you will still see the user warning about polar.out, but the code should run past that)

this work but have to much slow in performance

**Comment by andyweidong** [comment] 2023-07-24 09:05
参考这个试试：https://github.com/facebookresearch/llama/issues/50#issuecomment-1452527037

**Comment by REASY** [comment] 2023-07-27 10:52
In case you run Windows 10 as me, I had the same `RuntimeError: Distributed package doesn't have NCCL built in` error. To fix it I checked the code of Llama class https://github.com/facebookresearch/llama/blob/6c7fe276574e78057f917549435a2554000a876d/llama/generation.py#L61-L62 and saw how `torch.distributed` is initialized. One can check all possible backends at [distributed.html#torch.distributed.init_process_group](https://pytorch.org/docs/stable/distributed.html#torch.distributed.init_process_group). I changed the code to initialize it with `gloo` backend, `dist.init_process_group(backend="gloo")`

git diff:
```
Index: example_text_completion.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/example_text_completion.py b/example_text_completion.py
--- a/example_text_completion.py	(revision 6c7fe276574e78057f917549435a2554000a876d)
+++ b/example_text_completion.py	(date 1690453793087)
@@ -5,6 +5,9 @@
 
 from llama import Llama
 
+import torch
+import torch.distributed as dist
+
 
 def main(
     ckpt_dir: str,
@@ -15,6 +18,8 @@
     max_gen_len: int = 64,
     max_batch_size: int = 4,
 ):
+    dist.init_process_group(backend="gloo")
+
     generator = Llama.build(
         ckpt_dir=ckpt_dir,
         tokenizer_path=tokenizer_path,
@@ -52,4 +57,5 @@
 
 
 if __name__ == "__main__":
+    print("Cuda support:", torch.cuda.is_available(),":", torch.cuda.device_count(), "devices")
     fire.Fire(main)
```

After that change I was able to run 
```bash
(base) H:\github\facebook\llama>torchrun --standalone --nnodes=1 example_text_completion.py --ckpt_dir llama-2-7b/ --tokenizer_path tokenizer.model --max_seq_len 128 --max_batch_size 4
NOTE: Redirects are currently not supported in Windows or MacOs.
master_addr is only used for static rdzv_backend and when rdzv_endpoint is not specified.
Cuda support: True : 1 devices
> initializing model parallel with size 1
> initializing ddp with size 1
> initializing pipeline with size 1
Loaded in 13.40 seconds
I believe the meaning of life is
> to be happy. I believe we are all born with the potential to be happy. The meaning of life is to be happy, but the way to get there is not always easy.
The meaning of life is to be happy. It is not always easy to be happy, but it is possible. I believe that

==================================

Simply put, the theory of relativity states that
> 1) time, space, and mass are relative, and 2) the speed of light is constant, regardless of the relative motion of the observer.
Let’s look at the first point first.
Relative Time and Space
The theory of relativity is built on the idea that time and space are relative

==================================

A brief message congratulating the team on the launch:

        Hi everyone,

        I just
> wanted to say a big congratulations to the team on the launch of the new website.

        I think it looks fantastic and I'm sure it will be a huge success.

        I look forward to working with you all on the next project.

        Best wishes



==================================

Translate English to French:

        sea otter => loutre de mer
        peppermint => menthe poivrée
        plush girafe => girafe peluche
        cheese =>
> fromage
        fish => poisson
        giraffe => girafe
        elephant => éléphant
        cat => chat
        giraffe => girafe
        elephant => éléphant
        cat => chat
        giraffe => gira

==================================
```

Make sure you have enough RAM and GPU RAM, my RAM consumption when the model is loaded
![image](https://github.com/facebookresearch/llama/assets/5107562/01445191-4f55-4192-a4ad-c49deee21ad0)

GPU ram:
```
Thu Jul 27 18:48:46 2023
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 536.67                 Driver Version: 536.67       CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4090      WDDM  | 00000000:0C:00.0  On |                  Off |
| 30%   40C    P2             151W / 450W |  15160MiB / 24564MiB |     53%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
```

Note: I fixed `torchrun`, one can modify torchrun-script.py to make it work. In my case, I use miniconda, the full path is `c:\Users\User\miniconda3\Scripts\torchrun-script.py` and I had to fix the first line of that to point to the full path of Python shipped with miniconda:
```
#!c:\Users\User\miniconda3\python.exe
```

My env gathered via `python -m torch.utils.collect_env`
```
(base) H:\github\facebook\llama>python -m torch.utils.collect_env
Collecting environment information...
PyTorch version: 2.0.1
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Pro N
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.11.4 | packaged by Anaconda, Inc. | (main, Jul  5 2023, 13:47:18) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19045-SP0
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 4090
Nvidia driver version: 536.67
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=3493
DeviceID=CPU0
Family=107
L2CacheSize=8192
L2CacheSpeed=
Manufacturer=AuthenticAMD
MaxClockSpeed=3493
Name=AMD Ryzen 9 3950X 16-Core Processor
ProcessorType=3
Revision=28928

Versions of relevant libraries:
[pip3] numpy==1.25.0
[pip3] torch==2.0.1
[pip3] torchaudio==2.0.2+cu117
[pip3] torchvision==0.15.2+cu117
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               11.8.0               hd77b12b_0
[conda] mkl                       2023.1.0         h8bd8f75_46356
[conda] mkl-service               2.4.0           py311h2bbff1b_1
[conda] mkl_fft                   1.3.6           py311hf62ec03_1
[conda] mkl_random                1.2.2           py311hf62ec03_1
[conda] numpy                     1.25.1                   pypi_0    pypi
[conda] numpy-base                1.25.0          py311hd01c5d8_0
[conda] pytorch                   2.0.1           py3.11_cuda11.8_cudnn8_0    pytorch
[conda] pytorch-cuda              11.8                 h24eeafa_5    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torch                     2.0.1                    pypi_0    pypi
[conda] torchaudio                2.0.2+cu117              pypi_0    pypi
[conda] torchvision               0.15.2                   pypi_0    pypi
```

**Comment by MDFARHYN** [comment] 2023-07-30 00:10
Just initialized with `torch.distributed.init_process_group("gloo") ` go to the generation.py file and find the following line 
```
 if not torch.distributed.is_initialized():
            if device == "cuda":
                torch.distributed.init_process_group("nccl")
            else:
                torch.distributed.init_process_group("gloo") 
``` 

change it to 

```
 if not torch.distributed.is_initialized():
            if device == "cuda":
                 torch.distributed.init_process_group("gloo")
                
            else:
                torch.distributed.init_process_group("nccl")
```

**Comment by WuhanMonkey** [comment] 2023-09-06 16:38
Seems like the issue was resolved with suggestions above. Feel free to re-open as needed. Closing

**Closed by WuhanMonkey** 2023-09-06 16:38 UTC

**Comment by dunanyang** [comment] 2023-09-20 11:54
Why does we still don't have a solution to this error?

**Comment by psmyrdek** [comment] 2023-10-22 16:37
I've been able to start execution after applying changes similar to https://github.com/facebookresearch/codellama/pull/18/files

**Comment by pianistprogrammer** [comment] 2024-04-20 08:46
https://github.com/pianistprogrammer/llama3/tree/main, get this one, clone the repo, i have made changes to some files to make it work. You can find it in the commit tree

**Comment by haruelrovix** [comment] 2024-05-13 04:24
Hey @pianistprogrammer 👋🏻 

I tried your fork but got an error:

```
RuntimeError: Placeholder storage has not been allocated on MPS device!
```

It's M1 Pro. Any clue what is the issue?

---

Full logs:

```
(base) ➜  llama3-pianist git:(main) ✗ PYTORCH_ENABLE_MPS_FALLBACK=1 torchrun --nproc_per_node 1 example_text_completion.py --ckpt_dir Meta-Llama-3-8B-Instruct/ --tokenizer_path Meta-Llama-3-8B-Instruct/tokenizer.model --max_seq_len 128 --max_batch_size 4
W0513 11:17:12.135000 8470690496 torch/distributed/elastic/multiprocessing/redirects.py:27] NOTE: Redirects are currently not supported in Windows or MacOs.
> initializing model parallel with size 1
> initializing ddp with size 1
> initializing pipeline with size 1
/opt/miniconda3/lib/python3.12/site-packages/torch/__init__.py:747: UserWarning: torch.set_default_tensor_type() is deprecated as of PyTorch 2.1, please use torch.set_default_dtype() and torch.set_default_device() as alternatives. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/tensor/python_tensor.cpp:433.)
  _C._set_default_tensor_type(t)
Loaded in 37.49 seconds
[rank0]: Traceback (most recent call last):
[rank0]:   File "/llama3-pianist/example_text_completion.py", line 64, in <module>
[rank0]:     fire.Fire(main)
[rank0]:   File "/opt/miniconda3/lib/python3.12/site-packages/fire/core.py", line 143, in Fire
[rank0]:     component_trace = _Fire(component, args, parsed_flag_args, context, name)
[rank0]:                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/miniconda3/lib/python3.12/site-packages/fire/core.py", line 477, in _Fire
[rank0]:     component, remaining_args = _CallAndUpdateTrace(
[rank0]:                                 ^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/miniconda3/lib/python3.12/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
[rank0]:     component = fn(*varargs, **kwargs)
[rank0]:                 ^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/llama3-pianist/example_text_completion.py", line 51, in main
[rank0]:     results = generator.text_completion(
[rank0]:               ^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/llama3-pianist/llama/generation.py", line 282, in text_completion
[rank0]:     generation_tokens, generation_logprobs = self.generate(
[rank0]:                                              ^^^^^^^^^^^^^^
[rank0]:   File "/opt/miniconda3/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/llama3-pianist/llama/generation.py", line 201, in generate
[rank0]:     logits = self.model.forward(tokens[:, prev_pos:cur_pos], prev_pos)
[rank0]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/miniconda3/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/llama3-pianist/llama/model.py", line 291, in forward
[rank0]:     h = self.tok_embeddings(tokens)
[rank0]:         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/miniconda3/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/miniconda3/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/miniconda3/lib/python3.12/site-packages/fairscale/nn/model_parallel/layers.py", line 136, in forward
[rank0]:     output_parallel = F.embedding(
[rank0]:                       ^^^^^^^^^^^^
[rank0]:   File "/opt/miniconda3/lib/python3.12/site-packages/torch/nn/functional.py", line 2264, in embedding
[rank0]:     return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]: RuntimeError: Placeholder storage has not been allocated on MPS device!
E0513 11:17:57.237000 8470690496 torch/distributed/elastic/multiprocessing/api.py:826] failed (exitcode: 1) local_rank: 0 (pid: 5741) of binary: /opt/miniconda3/bin/python
Traceback (most recent call last):
  File "/opt/miniconda3/bin/torchrun", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/torch/distributed/run.py", line 879, in main
    run(args)
  File "/opt/miniconda3/lib/python3.12/site-packages/torch/distributed/run.py", line 870, in run
    elastic_launch(
  File "/opt/miniconda3/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 263, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
example_text_completion.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-05-13_11:17:57
  host      : 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 5741)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

**Comment by pianistprogrammer** [comment] 2024-05-13 18:11
I'm sorry about that, i have made a blog post on how to get it locally, https://questionbump.com/question/how-can-i-run-chatgpt-using-llms-locally/

**Comment by portah** [comment] 2025-01-18 03:50
This script is forced to use cuda, even if we change nccl to gloo
I was blindly adding, replacing any device="cuda" to "mps" and finally made it work

```
diff --git a/models/llama3/reference_impl/generation.py b/models/llama3/reference_impl/generation.py
index 6668f65..3439fb3 100644
--- a/models/llama3/reference_impl/generation.py
+++ b/models/llama3/reference_impl/generation.py
@@ -94,7 +94,7 @@ class Llama:
         """
 
         if not torch.distributed.is_initialized():
-            torch.distributed.init_process_group("nccl")
+            torch.distributed.init_process_group("gloo")
 
         if not model_parallel_is_initialized():
             if model_parallel_size is None:
@@ -102,7 +102,8 @@ class Llama:
             initialize_model_parallel(model_parallel_size)
 
         local_rank = int(os.environ.get("LOCAL_RANK", 0))
-        torch.cuda.set_device(local_rank)
+        #torch.cuda.set_device(local_rank)
+        device=torch.device("mps")
 
         torch.manual_seed(seed)
 
@@ -117,7 +118,7 @@ class Llama:
             checkpoints
         ), f"Loading a checkpoint for MP={len(checkpoints)} but world size is {model_parallel_size}"
         ckpt_path = checkpoints[get_model_parallel_rank()]
-        checkpoint = torch.load(ckpt_path, map_location="cpu", weights_only=True)
+        checkpoint = torch.load(ckpt_path, map_location="mps", weights_only=True)
         with open(Path(ckpt_dir) / "params.json", "r") as f:
             params = json.loads(f.read())
 
@@ -132,17 +133,18 @@ class Llama:
             tokenizer = Tokenizer.get_instance()
 
         assert model_args.vocab_size == tokenizer.n_words
-        if torch.cuda.is_bf16_supported():
-            torch.set_default_tensor_type(torch.cuda.BFloat16Tensor)
-        else:
-            torch.set_default_tensor_type(torch.cuda.HalfTensor)
+        #if torch.cuda.is_bf16_supported():
+        #    torch.set_default_tensor_type(torch.cuda.BFloat16Tensor)
+        #else:
+            #torch.set_default_tensor_type(torch.cuda.HalfTensor)
+        torch.set_default_dtype(torch.half)
         if model_args.vision_chunk_size > 0:
             from .multimodal.model import CrossAttentionTransformer
 
-            model = CrossAttentionTransformer(model_args)
+            model = CrossAttentionTransformer(model_args).to("mps")
             model.setup_cache(model_args.max_batch_size, torch.bfloat16)
         else:
-            model = Transformer(model_args)
+            model = Transformer(model_args).to("mps")
         model.load_state_dict(checkpoint, strict=True)
         print(f"Loaded in {time.time() - start_time:.2f} seconds")
 
@@ -207,14 +209,14 @@ class Llama:
             )
 
         pad_id = self.tokenizer.pad_id
-        tokens = torch.full((bsz, total_len), pad_id, dtype=torch.long, device="cuda")
+        tokens = torch.full((bsz, total_len), pad_id, dtype=torch.long, device="mps")
         for k, t in enumerate(prompt_tokens):
-            tokens[k, : len(t)] = torch.tensor(t, dtype=torch.long, device="cuda")
+            tokens[k, : len(t)] = torch.tensor(t, dtype=torch.long, device="mps")
         if logprobs:
-            token_logprobs = torch.zeros_like(tokens, dtype=torch.float)
+            token_logprobs = torch.zeros_like(tokens, dtype=torch.float, device="mps")
 
         prev_pos = 0
-        eos_reached = torch.tensor([False] * bsz, device="cuda")
+        eos_reached = torch.tensor([False] * bsz, device="mps")
         input_text_mask = tokens != pad_id
 
         if echo:
@@ -227,11 +229,11 @@ class Llama:
                     ),
                 )
 
-        stop_tokens = torch.tensor(self.tokenizer.stop_tokens)
+        stop_tokens = torch.tensor(self.tokenizer.stop_tokens).to("mps")
         for cur_pos in range(min_prompt_len, total_len):
             if is_vision:
                 position_ids = torch.arange(
-                    prev_pos, cur_pos, dtype=torch.long, device="cuda"
+                    prev_pos, cur_pos, dtype=torch.long, device="mps"
                 )
                 text_only_inference = model_input.vision is None
                 logits = self.model.forward(
@@ -251,7 +253,7 @@ class Llama:
             else:
                 next_token = torch.argmax(logits[:, -1], dim=-1)
 
-            next_token = next_token.reshape(-1)
+            next_token = next_token.reshape(-1).to("mps")
             # only replace token if prompt has already been generated
             next_token = torch.where(
                 input_text_mask[:, cur_pos], tokens[:, cur_pos], next_token
diff --git a/models/llama3/reference_impl/model.py b/models/llama3/reference_impl/model.py
index 099a1ed..a7a677e 100644
--- a/models/llama3/reference_impl/model.py
+++ b/models/llama3/reference_impl/model.py
@@ -64,14 +64,14 @@ def apply_scaling(freqs: torch.Tensor):
                 high_freq_factor - low_freq_factor
             )
             new_freqs.append((1 - smooth) * freq / scale_factor + smooth * freq)
-    return torch.tensor(new_freqs, dtype=freqs.dtype, device=freqs.device)
+    return torch.tensor(new_freqs, dtype=freqs.dtype, device="mps")
 
 
 def precompute_freqs_cis(
     dim: int, end: int, theta: float = 10000.0, use_scaled: bool = False
 ):
     freqs = 1.0 / (theta ** (torch.arange(0, dim, 2)[: (dim // 2)].float() / dim))
-    t = torch.arange(end, device=freqs.device, dtype=torch.float32)
+    t = torch.arange(end, device="mps", dtype=torch.float32)
     if use_scaled:
         freqs = apply_scaling(freqs)
     freqs = torch.outer(t, freqs)
@@ -157,16 +157,16 @@ class Attention(nn.Module):
                 args.max_seq_len,
                 self.n_local_kv_heads,
                 self.head_dim,
-            )
-        ).cuda()
+            ), device='mps'
+        ) # .cuda()
         self.cache_v = torch.zeros(
             (
                 args.max_batch_size,
                 args.max_seq_len,
                 self.n_local_kv_heads,
                 self.head_dim,
-            )
-        ).cuda()
+            ), device='mps'
+        ) #.cuda()
 
     def forward(
         self,
@@ -309,7 +309,7 @@ class Transformer(nn.Module):
 
         mask = None
         if seqlen > 1:
-            mask = torch.full((seqlen, seqlen), float("-inf"), device=tokens.device)
+            mask = torch.full((seqlen, seqlen), float("-inf"), device="mps") #tokens.device)
 
             mask = torch.triu(mask, diagonal=1)
 
@@ -324,7 +324,7 @@ class Transformer(nn.Module):
             # (seqlen, cache_len + seqlen), and the only masked entries are (i, j) for
             # j > cache_len + i, since row i corresponds to token cache_len + i.
             mask = torch.hstack(
-                [torch.zeros((seqlen, start_pos), device=tokens.device), mask]
+                [torch.zeros((seqlen, start_pos), device="mps"), mask]
             ).type_as(h)
 
         for layer in self.layers:
diff --git a/models/llama3/reference_impl/multimodal/model.py b/models/llama3/reference_impl/multimodal/model.py
index ca7a3c7..9d07bcc 100644
--- a/models/llama3/reference_impl/multimodal/model.py
+++ b/models/llama3/reference_impl/multimodal/model.py
@@ -477,7 +477,7 @@ class VisionEncoder(nn.Module):
             [
                 self.class_embedding.to(x.dtype)
                 + torch.zeros(
-                    x.shape[0], 1, x.shape[-1], dtype=x.dtype, device=x.device
+                    x.shape[0], 1, x.shape[-1], dtype=x.dtype, device="mps"
                 ),
                 x,
             ],
@@ -1407,7 +1407,7 @@ class CrossAttentionTransformer(torch.nn.Module):
         else:
             vision_tokens = self.vision_model(stacked_images, aspect_ratios)
 
-        vision_tokens = vision_tokens.to("cuda")
+        vision_tokens = vision_tokens.to("mps")
 
         bsz, nimg, nchunk, ntok, image_token_dim = tuple(vision_tokens.shape)
         xattn_caches = torch.stack(
@@ -1428,7 +1428,7 @@ class CrossAttentionTransformer(torch.nn.Module):
         cross_attention_masks, full_text_row_masked_out_mask = (
             self.text_model._get_xattn_mask(
                 num_tokens=total_len,
-                text_device="cuda",
+                text_device="mps",
                 text_dtype=next(self.text_model.parameters()).dtype,
                 vision_tokens=vision_tokens,
                 cross_attention_masks=padded_masks,

```

**Comment by Cypress98765** [comment] 2025-01-18 03:55
Look why dont you build a doctor ai to fix this shit ,and then I'm the
owner and will make lots of money , true story , I  own all rights to ai
doctors and beyond fuck yea I said it and if you come to my house Ilk splat
you

**Comment by Cypress98765** [comment] 2025-01-18 03:55
Why it gotta take stupid to fix shit , lol

**Comment by fooSynaptic** [comment] 2025-04-04 13:26
seems this issue not fixed yet, why closed
