### ISSUE TITLE
Meta model Conversion to the Hugging Face friendly version

### ISSUE THREAD

**Issue by Yarmohamadshr** [facebookresearch/llama#908] opened 2023-11-07 17:44 UTC
Hi,
I am trying to use the meta LLam2 I downloaded from Meta, but it has problem that needs to be converted to Hugging Face friendly version, I can not use the ones in Hugging Face because the GPU server I am using cannot connect to the internet. So, I saw the code for conversion, but it is not clear where to run the code. Also, the input path should be the directory where I have all the files with Tokenizer and mode, or the path that is just for the model and contains .chk .chk and .json for the weights? I would appreciate it if someone could help me with this problem, I stuck like 2 weeks.

**Comment by subramen** [comment] 2023-11-08 13:52
Hi, closing this thread as it is a duplicate of your open issue at https://github.com/facebookresearch/llama/issues/904. Please continue the discussion there. Thanks

**Closed by subramen** 2023-11-08 13:52 UTC
Labels: duplicate
